### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by wiesehahn** [Martinomagnifico/quarto-verticator#1]
I cannot install the extension as specified with `quarto add martinomagnifico/quarto-verticator`

Trying to install the extension in the way other extensions are installed (`quarto install extension Martinomagnifico/quarto-verticator`) also does not work.

What am I supposed to do?

**Comment by Martinomagnifico** [comment]
Hi Jens, that's really strange. Both ways of installing work for me. Do you have Quarto 1.2 installed?

**Comment by wiesehahn** [comment]
Thanks, I updated to 1.2 and now installation seems to work. 
However, I am still not able to use it. Rendering the document returns `ERROR: Specified Reveal plugin directory 'verticator' does not exist.`

**Comment by Martinomagnifico** [comment]
Hi Jens, that's also strange. Quarto will look into your _extensions directory for plugins, and find them even if there is an extra namespace. Did you add the plugin to the page like below?

```
revealjs-plugins:
  - verticator
```

**Comment by wiesehahn** [comment]
I found the reason its not working.

In my case the quarto file (qmd) lays in a subfolder of the project. But installing extensions creates the _extensions folder in the project root directory, where it is not found when rendering from within the subfolder. 

It can be fixed by moving either the qmd file or the _extensions folder to one folder level.

**Comment by Martinomagnifico** [comment]
Thanks, I’ll change the docs to indicate the relation between install location and referring file. By the way, forestry is cool. Nice viz of Harz mountains, but needed to login into Vimeo to be able to watch the “Webmapping” video, no preview otherwise.
